[default]
playwright_headless = false
aws_s3_bucket = "flashlight-assets"
aws_s3_prefix = "/assets/"
aws_region = "us-east-2"
llm_model_name = "gpt-4.1"
llm_temperature = 0.7
llm_provider = "openai"

